name: NATO Taleo Yesterday Test

on:
  workflow_dispatch:       # Manuel çalıştırma butonu
  schedule:
    - cron: "0 */6 * * *"  # Her 6 saatte bir (istersen 3 saate düşürebilirsin)

jobs:
  run-yesterday-test:
    runs-on: ubuntu-latest

    steps:
      - name: Kodu al
        uses: actions/checkout@v4

      - name: Chrome kur
        uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: stable

      - name: Python kur
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Bağımlılıkları yükle
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Yesterday test scriptini çalıştır
        env:
          CHROME_PATH: ${{ env.CHROME_PATH }}
          CHROME_BIN: ${{ env.CHROME_BIN }}
        run: |
          python taleo_yesterday_test.py