name: NATO Taleo Yesterday Test 2

on:
  workflow_dispatch:       # Elle tetikleme
  schedule:
    - cron: "0 */6 * * *"  # Opsiyonel: 6 saatte bir

jobs:
  run-yesterday-test:
    runs-on: ubuntu-latest

    steps:
      - name: Kodu al
        uses: actions/checkout@v4

      - name: Log testi (çıktı var mı?)
        run: |
          echo "Workflow başladı ✅"
          python --version
          uname -a

      - name: Chrome kur
        id: setup-chrome
        uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: stable

      - name: Python kur
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Bağımlılıkları yükle
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Yesterday test scriptini çalıştır
        env:
          # setup-chrome çıktılarından path alıyoruz (env değil, outputs!)
          CHROME_PATH: ${{ steps.setup-chrome.outputs.chrome-path }}
          CHROME_BIN:  ${{ steps.setup-chrome.outputs.chrome-path }}
        run: |
          python taleo_yesterday_test.py

      # İsteğe bağlı: ham HTML/çıktıları artefact olarak kaydetmek için
      - name: Çıktı yoksa da job logunu garanti et
        run: echo "Job tamamlandı."